In [73]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sn

# Loading dataset

In [74]:
df = pd.read_csv("bank_dataset.csv")
df.head()

ID  Age  Experience  Income  ZIP Code  Family  CCAvg  Education  Mortgage  \
0   1   25           1      49     91107       4    1.6          1         0   
1   2   45          19      34     90089       3    1.5          1         0   
2   3   39          15      11     94720       1    1.0          1         0   
3   4   35           9     100     94112       1    2.7          2         0   
4   5   35           8      45     91330       4    1.0          2         0   

   Personal Loan  Securities Account  CD Account  Online  CreditCard  
0              0                   1           0       0           0  
1              0                   1           0       0           0  
2              0                   0           0       0           0  
3              0                   0           0       0           0  
4              0                   0           0       0           1

In [75]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   ID                  5000 non-null   int64  
 1   Age                 5000 non-null   int64  
 2   Experience          5000 non-null   int64  
 3   Income              5000 non-null   int64  
 4   ZIP Code            5000 non-null   int64  
 5   Family              5000 non-null   int64  
 6   CCAvg               5000 non-null   float64
 7   Education           5000 non-null   int64  
 8   Mortgage            5000 non-null   int64  
 9   Personal Loan       5000 non-null   int64  
 10  Securities Account  5000 non-null   int64  
 11  CD Account          5000 non-null   int64  
 12  Online              5000 non-null   int64  
 13  CreditCard          5000 non-null   int64  
dtypes: float64(1), int64(13)
memory usage: 547.0 KB


In [76]:
df.describe()

ID          Age   Experience       Income      ZIP Code  \
count  5000.000000  5000.000000  5000.000000  5000.000000   5000.000000   
mean   2500.500000    45.338400    20.104600    73.774200  93152.503000   
std    1443.520003    11.463166    11.467954    46.033729   2121.852197   
min       1.000000    23.000000    -3.000000     8.000000   9307.000000   
25%    1250.750000    35.000000    10.000000    39.000000  91911.000000   
50%    2500.500000    45.000000    20.000000    64.000000  93437.000000   
75%    3750.250000    55.000000    30.000000    98.000000  94608.000000   
max    5000.000000    67.000000    43.000000   224.000000  96651.000000   

            Family        CCAvg    Education     Mortgage  Personal Loan  \
count  5000.000000  5000.000000  5000.000000  5000.000000    5000.000000   
mean      2.396400     1.937938     1.881000    56.498800       0.096000   
std       1.147663     1.747659     0.839869   101.713802       0.294621   
min       1.000000     0.000000     1.000000     0.000000       0.000000   
25%       1.000000     0.700000     1.000000     0.000000       0.000000   
50%       2.000000     1.500000     2.000000     0.000000       0.000000   
75%       3.000000     2.500000     3.000000   101.000000       0.000000   
max       4.000000    10.000000     3.000000   635.000000       1.000000   

       Securities Account  CD Account       Online   CreditCard  
count         5000.000000  5000.00000  5000.000000  5000.000000  
mean             0.104400     0.06040     0.596800     0.294000  
std              0.305809     0.23825     0.490589     0.455637  
min              0.000000     0.00000     0.000000     0.000000  
25%              0.000000     0.00000     0.000000     0.000000  
50%              0.000000     0.00000     1.000000     0.000000  
75%              0.000000     0.00000     1.000000     1.000000  
max              1.000000     1.00000     1.000000     1.000000

# a.) predict unseen data with KNN k =3

In [77]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split

x = df[df.columns.drop(["ZIP Code","ID","Personal Loan"])]
y = df["Personal Loan"]

x_train,x_test,y_train,y_test = train_test_split(x,y)

model = KNeighborsClassifier(n_neighbors=3)
model.fit(x_train,y_train)
model.score(x_test,y_test)

0.9152

In [78]:
new_df = pd.read_csv("bank_new.csv")
new_df.head()

Age  Experience  Income  Family  CCAvg  Education  Mortgage  Personal Loan  \
0   40          10      84       2      2          2         0            NaN   

   Securities Account  CD Account  Online  CreditCard  
0                   0           0       1           1

In [79]:
model.predict(new_df[new_df.columns.drop("Personal Loan")])

array([0])

# b.) Partition the data into training (60%) and validation (40%) sets. Show the classification matrix for the test data that results by varying k.

In [83]:
from sklearn.metrics import confusion_matrix, classification_report
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.4)

scores = []

for i in range(1,10):
    model = KNeighborsClassifier(n_neighbors=i)
    model.fit(x_train,y_train)
    predict = model.predict(x_test)
    print("k =",i)
    print(confusion_matrix(y_true=y_test,y_pred=predict))
    print(classification_report(y_test,predict))
    print(model.score(x_test,y_test))
    print("\n")
    scores.append({i:model.score(x_test,y_test)})
print(sorted(scores,key=lambda x:list(x.values())[0],reverse=True))

k = 1
[[1707  102]
 [ 106   85]]
              precision    recall  f1-score   support

           0       0.94      0.94      0.94      1809
           1       0.45      0.45      0.45       191

    accuracy                           0.90      2000
   macro avg       0.70      0.69      0.70      2000
weighted avg       0.90      0.90      0.90      2000

0.896


k = 2
[[1777   32]
 [ 150   41]]
              precision    recall  f1-score   support

           0       0.92      0.98      0.95      1809
           1       0.56      0.21      0.31       191

    accuracy                           0.91      2000
   macro avg       0.74      0.60      0.63      2000
weighted avg       0.89      0.91      0.89      2000

0.909


k = 3
[[1719   90]
 [ 123   68]]
              precision    recall  f1-score   support

           0       0.93      0.95      0.94      1809
           1       0.43      0.36      0.39       191

    accuracy                           0.89      2000
   macro avg 

# c.) Propose your best model

predict with KNN k=2

In [84]:
model = KNeighborsClassifier(n_neighbors=2)
model.fit(x_train,y_train)
model.predict(new_df[new_df.columns.drop("Personal Loan")])

array([0])